### ISSUE TITLE
Is there is type error. 

### ISSUE THREAD

**Issue by Altaf-hucn** [EscVM/EscVM_YT#1]
Thank for sharing the code. when i run your code in spyder IDE it give me error in the "**class ChannelAttention**" class. How to remove this error. Thank you.
**Bellow is the visual of your code.**
![Clean Att](https://user-images.githubusercontent.com/19892199/125165379-99d1a580-e1d1-11eb-9de7-d911ba40e5d5.png)

**Comment by EscVM** [comment]
Hi @Altaf-hucn,

I'm really sorry for that little bug. I'm gonna correct it immediately.

If you refer to the CBAM [architecture](https://media.springernature.com/original/springer-static/image/chp%3A10.1007%2F978-3-030-01234-2_1/MediaObjects/474212_1_En_1_Fig2_HTML.gif), you notice that the input goes through two parallel paths: the Global Max Pooling and Global Average Pooling ones. So, in the notebook, x should be input.

**Comment by EscVM** [comment]
Ok, now it should work just fine! 

Good luck for your work!
